name: README to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'TP_TLS_leonard.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: TP_TLS_leonard.md
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
          template: template.html
          table_of_contents: true
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs/TP_TLS_leonard.pdf

